### PR TITLE
chore(400-claims.md): update version in anticipation of the 1.0.0 release

### PR DESCRIPTION
**Pull request by vdice**
Version and text updates for the forthcoming proposed CNAB Claims 1.0.0 release

Ref https://github.com/cnabio/cnab-spec/issues/389

### CODE REVIEW

**Review by carolynvs — APPROVED** [review]
LGTM

**Review by chris-crone — APPROVED** [review]
LGTM

**Review by radu-matei — APPROVED** [review]

**Review by technosophos — APPROVED** [review]
An enthusiastic LGTM from me! I know this proposal took much more work than any of us expected. Thank you all for working through detail after detail.

**Comment by technosophos** [comment]
@jeremyrickard @silvin-lubecki @jlegrone If you have a moment to vote on this, it would be appreciated

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Review by jlegrone — APPROVED** [review]

**Pull request merged**
