### PR TITLE
CNAB Security 1.0 GA

### PR DESCRIPTION
**Pull request by radu-matei**
This commit marks the Working Group Acceptance (GA) of the CNAB Security 1.0 specification.

According to the [OWNERS](https://github.com/cnabio/cnab-spec/blob/master/OWNERS) file, the following people must vote:

@radu-matei
@technosophos
@jeremyrickard
@silvin-lubecki
@jlegrone
@carolynvs 

cc @chris-crone, @trishankatdatadog, @squillace

### CODE REVIEW

**Comment by squillace** [comment]
fantastic work, actually. amazing, tremendous labors all. On to the example and blog for it!!!!

**Comment by carolynvs** [comment]
So say we all 💯

**Comment by technosophos** [comment]
Can someone put this on a branch that @chris-crone and I can vote on and tag? I think @vdice is the resident expert on this process.

**Comment by vdice** [comment]
@technosophos the [cnab-security-1.0.0-ga](https://github.com/cnabio/cnab-spec/tree/cnab-security-1.0.0-ga) branch has now been created.  It sounds like we'll wait on creation of the tag until the vote has been held.

**Comment by technosophos** [comment]
Chris and I both voted on this issue, but met today and re-confirmed that we believe the proposal is ready for release. Therefore, this proposal has been ratified.

**Pull request merged**
