### PR TITLE
feat(ci): publish versioned schema

### PR DESCRIPTION
**Pull request by vdice**
* adds CI for publishing schema on git tag pushes
* adds entry on where to find published schema in README
* refactors brigade.js with latest brigade-utils helpers

Contributes towards https://github.com/cnabio/cnab-spec/issues/346
Depends on https://github.com/cnabio/cnab.io/pull/32 (merged)

TODO (after approval):

 - [ ] update PR check from `validation` to `cnab-spec-validate`:

Screen Shot 2020-03-10 at 1 52 11 PM

### CODE REVIEW

**Comment by vdice** [comment]
@technosophos I just realized the following:  I had centered CI around git tags but I now recall that we have a precedent of pushing spec versions to separate branches.  Can we change the process to instead cut tags for each future spec version?  Or should I adjust this process to trigger on branch creation?  (May be trickier to ignore potential non-version-related branches, etc.)

**Comment by vdice** [comment]
> @technosophos I just realized the following: I had centered CI around git tags but...

Discussion transitioned to https://github.com/cnabio/cnab-spec/issues/351

**Comment by technosophos** [comment]
I think we can publish a tag for 1.0.1 if we need to get this working.

**Comment by vdice** [comment]
> I think we can publish a tag for 1.0.1 if we need to get this working.

It looks like a tag can't be pushed with the same name of a branch.  I've manually uploaded the schema artifacts from the `cnab-core-1.0.1` branch as a stop-gap 👍 .

**Pull request merged**
