### PR TITLE
CNAB Core 1.0.1

### PR DESCRIPTION
**Pull request by technosophos**
This PR is the candidate release for CNAB Core 1.0.1

The following people need to vote on ratifying this specification:

@radu-matei
@simonferquel
@technosophos
@jeremyrickard
@silvin-lubecki

The following changes have been included as part of CNAB 1.0.1:

- CNAB Core 1.0.1 da244afe71c1a8ff3ce4e7f5fd1aecaea0fbd885 (Matt Butcher)
- removed unnecessary references to the original authors' registries (#321) 36d7b4817de6902142fc338549c8d93aa94b37a5 (Matt Butcher)
- Update 103-bundle-runtime.md 9b624dc74af9efc3ce05b571379ccc6248f59acc (Matt Butcher)
- Re-added JSON-ish encoding suggestions aae4578835314c769ba57ff143031c572726aa7a (Matt Butcher)
- Minimal changeset for fixing 319 d6c0505c40120a53050c9a7051d761eefe5da294 (Matt Butcher)
- replaced ambiguous description of environment variable content d20292c374ade98fb00c70dc72254c0d6df45b24 (Matt Butcher)
- Update 103-bundle-runtime.md 348e60422e45a576475290f4a245b137f2e3c831 (Ventsislav Potchekanski)
- Bump bundle schemaVersion to 1.0.0 (#278) 5ad8019d1624afb5a0c5a661332a6e133cddac57 (Chris Crone)

Signed-off-by: Matt Butcher <matt.butcher@microsoft.com>

### CODE REVIEW

**Comment by technosophos** [comment]
I vote 👍

**Comment by chris-crone** [comment]
@rumpl caught last time we cut a release that we didn't update the `101-bundle-json.md`. Doing:
```console
$ git grep 1\.0\.\0
```

I see that we still have:
```console
...
101-bundle-json.md:- The schema version of the bundle, as a string with a `v` prefix. This schema is to be referenced as `v1` or `v1.0.0`
101-bundle-json.md:   "schemaVersion":"v1.0.0",
101-bundle-json.md:{"credentials":{"hostkey":{"env":"HOST_KEY","path":"/etc/hostkey.txt"}},"custom":{"com.example.backup-preferences":{"frequency":"daily"},"com.example.duffle-bag":{"icon":"https://example.com/icon.png","iconType":"PNG"}},"definitions":{"http_port":{"default":80,"maximum":10240,"minimum":10,"type":"integer"},"port":{"maximum":65535,"minimum":1024,"type":"integer"},"string":{"type":"string"},"x509Certificate":{"contentEncoding":"base64","contentMediaType":"application/x-x509-user-cert","type":"string","writeOnly":true}},"description":"An example 'thin' helloworld Cloud-Native Application Bundle","images":{"my-microservice":{"contentDigest":"sha256:aaaaaaaaaaaa...","description":"my microservice","image":"example/microservice:1.2.3"}},"invocationImages":[{"contentDigest":"sha256:aaaaaaa...","image":"example/helloworld:0.1.0","imageType":"docker"}],"maintainers":[{"email":"matt.butcher@microsoft.com","name":"Matt Butcher","url":"https://example.com"}],"name":"helloworld","outputs":{"clientCert":{"definition":"x509Certificate","path":"/cnab/app/outputs/clientCert"},"hostName":{"applyTo":["install"],"definition":"string","description":"the hostname produced installing the bundle","path":"/cnab/app/outputs/hostname"},"port":{"definition":"port","path":"/cnab/app/outputs/port"}},"parameters":{"backend_port":{"definition":"http_port","description":"The port that the back-end will listen on","destination":{"env":"BACKEND_PORT"}}},"schemaVersion":"v1.0.0","version":"0.1.2"}
101-bundle-json.md:   "schemaVersion":"v1.0.0",
101-bundle-json.md:   "version":"1.0.0"
101-bundle-json.md:The current schema version is `v1.0.0`, which is considered stable.
101-bundle-json.md:   "schemaVersion":"v1.0.0",
...
examples/101.01-bundle.json:  "schemaVersion": "v1.0.0",
examples/101.02-bundle.json:  "schemaVersion": "v1.0.0",
examples/101.02-bundle.json:  "version": "1.0.0"
examples/101.03-bundle.json:  "schemaVersion": "v1.0.0",
examples/400.01-claim.json:    "schemaVersion": "v1.0.0",
```

I think it would make the spec clearer if we use the current version in these places.

**Comment by technosophos** [comment]
Thanks for catching those @chris-crone . I acknowledge your grepping skills as superior to my own. 😄 I have fixed those instances.

**Comment by technosophos** [comment]
Just awaiting an LGTM from @simonferquel

**Comment by technosophos** [comment]
At the CNAB meeting this morning, we finalized the decision to commit this. I am pushing it to branch cnab-core-v1.0.1.

**Comment by technosophos** [comment]
https://github.com/cnabio/cnab-spec/tree/cnab-core-1.0.1

**Pull request closed without merging**
